---
# handlers file for postfix

- name: start postfix
  service:
    name: postfix
    state: started

- name: stop postfix
  service:
    name: postfix
    state: stopped

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: restart postfix
  service:
    name: postfix
    state: restarted
