---
# handlers file for postfix

- name: start postfix
  service:
    name: postfix
    state: started
    pattern: /usr/libexec/postfix/master

- name: stop postfix
  service:
    name: postfix
    state: stopped

- name: reload postfix
  service:
    name: postfix
    state: reloaded
